language: ruby
rvm:
  - 2.1.1
env: TEST_DATABASE=prx_test RAILS_ENV=test RAILS_SECRET_KEY=secret AWS_BUCKET=travis AWS_ACCESS_KEY_ID=aaki AWS_SECRET_ACCESS_KEY=asak PUBLIC_ASSET_SECRET=secret
bundler_args: --without development
services: mysql
before_script:
  - mysqladmin create prx_test
addons:
  code_climate:
    repo_token: 78c896adecc52c38b7778a7e7b3c28193798a9fac704dddc3a506006b948e591
