version: '2'
networks:
  cms-net:
    driver: bridge
volumes:
    esdata1:
services:
  cms:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    depends_on:
      - db
      - pg
      - elasticsearch
    ports:
      - "3002:3000"
    command: web
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: cms.prx.docker
      LOCAL_ENV: "true"
    networks:
      - cms-net
  worker:
    image: cmsprxorg_cms
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      LOCAL_ENV: "true"
    depends_on:
      - db
      - elasticsearch
    command: worker
    networks:
      - cms-net
  db:
    image: mysql:8.0.12
    env_file:
      - .env
    expose:
      - "3306"
    command: mysqld --log_error_verbosity=1 --default-authentication-plugin=mysql_native_password
    networks:
      - cms-net
  pg:
    image: postgres
    env_file:
      - .env
    expose:
      - "5432"
    volumes:
      - ./test/db/:/docker-entrypoint-initdb.d/
    networks:
      - cms-net
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - cms-net
