cms:
  build: .
  volumes:
    - .:/app
  env_file:
    - .env
  links:
    - db
  ports:
    - "3000:3000"
  command: web
  environment:
    VIRTUAL_HOST: cms.prx.docker
    LOCAL_ENV: "true"
    DB_ENV_MYSQL_USER: root
    DB_ENV_MYSQL_PASSWORD: password
    DB_PORT_3306_TCP_ADDR: db
    DB_PORT_3306_TCP_PORT: "3306"
  # tty: true
  # stdin_open: true
worker:
  image: cmsprxorg_cms
  volumes:
    - .:/app
  env_file:
    - .env
  environment:
    LOCAL_ENV: "true"
    DB_ENV_MYSQL_USER: root
    DB_ENV_MYSQL_PASSWORD: password
    DB_PORT_3306_TCP_ADDR: db
    DB_PORT_3306_TCP_PORT: "3306"
  links:
    - db
  command: worker
db:
  image: mysql
  env_file:
    - .env
  environment:
    MYSQL_DATABASE: cms_development
    MYSQL_ROOT_PASSWORD: password
  ports:
    - "3306:3306"
  command: mysqld --log_error_verbosity=1
