version: '2'
services:
  cms:
    build: .
    links:
      - db
      - pg
      - elasticsearch
    ports:
      - 3000:3000
    command: test
    env_file:
      - env-example
    environment:
      VIRTUAL_HOST: cms.prx.docker
      LOCAL_ENV: "true"
      DB_ENV_MYSQL_USER: root
      DB_ENV_MYSQL_PASSWORD: password
      DB_PORT_3306_TCP_ADDR: db
      DB_PORT_3306_TCP_PORT: "3306"
      FEEDER_DB_HOST: pg
      FEEDER_DB_DATABASE: feeder
      FEEDER_DB_PASSWORD: password
      ELASTICSEARCH_URL: http://elasticsearch:9200
  db:
    image: mysql:8.0.2
    environment:
      MYSQL_DATABASE: cms_test
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    command: mysqld --log_error_verbosity=1 --default-authentication-plugin=mysql_native_password
  pg:
    image: postgres
    env_file:
      - env-example
    environment:
      POSTGRES_USER: feeder
      POSTGRES_PASSWORD: password
      POSTGRES_DB: feeder
    ports:
      - 5432:5432
    volumes:
      - ./test/db/:/docker-entrypoint-initdb.d/
  elasticsearch:
    image: elasticsearch:6.4.3
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
volumes:
  esdata1:
