# Configuration file that defines the settings for pub/sub of events
app_name: cms

publish:
  story:
    - create
    - update
    - delete
    - publish
    - unpublish
  series:
    - create
    - update
    - delete
  image:
    - create
    - update
    - delete
  audio:
    - create
    - update
    - delete
